--- !ruby/object:Resume::ResumeConfig 
achievement_tags: 
- :lead
- :pm
- :architect
alt_tag: :developer
core_name: techlead
include_untagged_achievements: true
max_achievements: 3
min_achievements: 3
primary_tag: :architect
