--- !ruby/object:Claret::Project 
items: 
- !ruby/object:Claret::Task 
  contributes_to: []

  dependents: []

  id: 1
  name: Better conditional generation for headline and summary
- &id002 !ruby/object:Claret::Task 
  contributes_to: 
  - &id003 !ruby/object:Claret::Task 
    contributes_to: []

    dependents: 
    - *id002
    id: 3
    name: GEM packaging
  dependents: []

  finish_date: &id001 2008-10-26 18:18:14.966252 -04:00
  id: 2
  name: Command Line interface
  start_date: *id001
- *id003
- !ruby/object:Claret::Task 
  contributes_to: []

  dependents: []

  id: 4
  name: don't hardcode the skill categories
- &id007 !ruby/object:Claret::Task 
  contributes_to: 
  - &id005 !ruby/object:Claret::Milestone 
    dependents: 
    - *id007
    - &id008 !ruby/object:Claret::Task 
      contributes_to: 
      - *id005
      dependents: []

      finish_date: &id004 2008-10-26 18:18:01.303956 -04:00
      id: 8
      name: Use ERB for RTF
      start_date: *id004
    estimated_achieve_date: 
    id: 9
    name: Using ERB instead of custom code for formatting
  dependents: []

  finish_date: &id006 2008-10-26 14:59:14.255221 -04:00
  id: 7
  name: Use ERB for Markdown
  start_date: *id006
- *id008
- *id005
- !ruby/object:Claret::Task 
  contributes_to: []

  dependents: []

  id: 10
  name: Restore the achievement filtering stuff
name: Dave's Resume
next_id: 11
